"""Write .git/hooks/post-commit + pre-push shims, chmod 0o755.

Owner: Dev D
Tier: 6 — may import from: everything below tier 6
See docs/architecture.md
"""

from __future__ import annotations

import stat
from pathlib import Path

# `sh`, not `bash`: Git for Windows runs hooks through its bundled sh, and a
# bash-only shebang is the classic "works on my machine" hook.
#
# There is no `--sha` flag here. There used to be — `yeet run --event push --sha
# $(git rev-parse HEAD)` — and `yeet run` has never had that option, so every
# installed post-commit hook failed with "No such option: --sha" and D27's
# "git commit fires a run" could not have worked. It is not needed either:
# `build_github_context` reads `.git/HEAD` itself, and by the time post-commit
# runs, HEAD is already the new commit.
POST_COMMIT_SCRIPT = """#!/bin/sh
# Generated by yeet -- do not hand edit
# Hooks can run from a subdirectory; the flow paths are relative to the root.
cd "$(git rev-parse --show-toplevel)" || exit 0
yeet run --event push
"""

# post-commit cannot fail a commit that already happened, but pre-push can stop
# a push, so `|| true` is what makes non-blocking mean non-blocking.
PRE_PUSH_SCRIPT_NONBLOCKING = """#!/bin/sh
# Generated by yeet -- do not hand edit
cd "$(git rev-parse --show-toplevel)" || exit 0
yeet check --strict || true
"""

PRE_PUSH_SCRIPT_BLOCKING = """#!/bin/sh
# Generated by yeet -- do not hand edit
cd "$(git rev-parse --show-toplevel)" || exit 1
yeet check --strict
"""


MARKER = "Generated by yeet"


class HookExists(RuntimeError):
    """A hook is already there and we did not write it."""


def install(root: Path, blocking: bool = False, *, force: bool = False) -> list[Path]:
    """Install git hook shims into .git/hooks/. Named per plan.md §4.

    Refuses to clobber a hook yeet did not write. A repo with its own
    `pre-push` is common, that hook is often the only thing standing between
    the team and a bad push, and silently replacing it would be the single
    most destructive thing this tool could do to a repo it was pointed at.
    Re-running over yeet's own hooks is fine — that is how `--blocking` is
    toggled.
    """
    git_hooks_dir = root / ".git" / "hooks"
    if not git_hooks_dir.exists():
        raise FileNotFoundError(f"Git hooks directory not found at {git_hooks_dir}")

    wanted = {
        "post-commit": POST_COMMIT_SCRIPT,
        "pre-push": PRE_PUSH_SCRIPT_BLOCKING if blocking else PRE_PUSH_SCRIPT_NONBLOCKING,
    }

    if not force:
        for name in wanted:
            path = git_hooks_dir / name
            if path.exists() and MARKER not in _read(path):
                raise HookExists(
                    f"{path} already exists and was not written by yeet. "
                    f"Move it aside, or re-run with --force to replace it."
                )

    installed: list[Path] = []
    for name, script in wanted.items():
        path = git_hooks_dir / name
        path.write_text(script, encoding="utf-8")
        _make_executable(path)
        installed.append(path)
    return installed


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def uninstall(root: Path) -> list[Path]:
    """Remove only hooks written by yeet."""
    git_hooks_dir = root / ".git" / "hooks"
    if not git_hooks_dir.exists():
        return []

    removed: list[Path] = []
    for hook_name in ("post-commit", "pre-push"):
        hook_path = git_hooks_dir / hook_name
        # Only ever remove our own — see `install`.
        if hook_path.exists() and MARKER in _read(hook_path):
            try:
                hook_path.unlink()
                removed.append(hook_path)
            except OSError:
                pass

    return removed


def _make_executable(path: Path) -> None:
    try:
        current = path.stat().st_mode
        path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except Exception:
        pass
