"""Write .git/hooks/post-commit + pre-push shims, chmod 0o755.

Owner: Dev D
Tier: 6 — may import from: everything below tier 6
See docs/architecture.md
"""

from __future__ import annotations

import stat
from pathlib import Path

POST_COMMIT_SCRIPT = """#!/bin/sh
# Generated by yeet -- do not hand edit
yeet run --event push --sha $(git rev-parse HEAD)
"""

PRE_PUSH_SCRIPT_NONBLOCKING = """#!/bin/sh
# Generated by yeet -- do not hand edit
yeet check --strict || true
"""

PRE_PUSH_SCRIPT_BLOCKING = """#!/bin/sh
# Generated by yeet -- do not hand edit
yeet check --strict
"""


def install_hooks(root: Path, blocking: bool = False) -> list[Path]:
    """Install git hook shims into .git/hooks/."""
    git_hooks_dir = root / ".git" / "hooks"
    if not git_hooks_dir.exists():
        raise FileNotFoundError(f"Git hooks directory not found at {git_hooks_dir}")

    installed: list[Path] = []

    post_commit = git_hooks_dir / "post-commit"
    post_commit.write_text(POST_COMMIT_SCRIPT, encoding="utf-8")
    _make_executable(post_commit)
    installed.append(post_commit)

    pre_push = git_hooks_dir / "pre-push"
    script = PRE_PUSH_SCRIPT_BLOCKING if blocking else PRE_PUSH_SCRIPT_NONBLOCKING
    pre_push.write_text(script, encoding="utf-8")
    _make_executable(pre_push)
    installed.append(pre_push)

    return installed


def uninstall_hooks(root: Path) -> list[Path]:
    """Remove only hooks written by yeet."""
    git_hooks_dir = root / ".git" / "hooks"
    if not git_hooks_dir.exists():
        return []

    removed: list[Path] = []
    for hook_name in ("post-commit", "pre-push"):
        hook_path = git_hooks_dir / hook_name
        if hook_path.exists():
            try:
                content = hook_path.read_text(encoding="utf-8")
                if "Generated by yeet" in content:
                    hook_path.unlink()
                    removed.append(hook_path)
            except Exception:
                pass

    return removed


def _make_executable(path: Path) -> None:
    try:
        current = path.stat().st_mode
        path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except Exception:
        pass
